### PR TITLE
Allow data attributes

### PR DESCRIPTION
**Pull request by vladitot**
Request as Decision for https://github.com/orchidsoftware/platform/pull/1232

### CODE REVIEW

**Comment by tabuna** [comment]
Hey. I think we can write this much better by changing the `getAllowAttributes` method itself.

```php
    /**
     * @return Collection
     */
    protected function getAllowAttributes(): Collection
    {
        $allow = array_merge($this->universalAttributes, $this->inlineAttributes);

        return collect($this->getAttributes())->filter(function ($attribute) use ($allow) {
            return Str::is($allow, $attribute);
        });
    }
```

Something like that. Then we give in `universalAttributes` value `data-*`.
This will fit the pattern and all date attributes can be recorded, but at the same time excluded if necessary.
This also requires confirmation with a test. Tell me if you need help

**Comment by vladitot** [comment]
@tabuna look please, is it right way?

**Comment by tabuna** [comment]
Yes, the meaning is. But this code doesn't work on some `php/laravel` versions, which is signaled by tests.
https://github.com/orchidsoftware/platform/pull/1240/checks?check_run_id=1128384557

**Comment by tabuna** [comment]
Hey @vladitot. Have you looked at the previous post? Do you need help?

**Comment by tabuna** [comment]
https://github.com/orchidsoftware/platform/releases/tag/8.3.0

**Comment by vladitot** [comment]
@tabuna Thank you for your help. There was weekends, so I couldn't finish request.

**Pull request closed without merging**
