### PR TITLE
Add close icon for selected filters

### PR DESCRIPTION
**Pull request by grigoriy-ivanov**
Before
изображение

After
изображение

### CODE REVIEW

**Comment by tabuna** [comment]
Hey @grigoriy-ivanov. Don't your users understand these badges? Or do you think it would be better this way?

**Comment by grigoriy-ivanov** [comment]
Yes, they don't. 
I think it looks better this way, like a multiple select field with selected options.
Examples:
Ozon:
изображение
DNS:
изображение

**Comment by tabuna** [comment]
Ping @Hesko ^

**Comment by tabuna** [comment]
@grigoriy-ivanov Thanks a lot. We changed it a bit and made a release.

**Pull request closed without merging**
