### PR TITLE
Translation to portuguese file acess.md

### PR DESCRIPTION
**Pull request by nunojesus**
Hello, I translated this file into Portuguese from Portugal.
Please let me know if what I've done is alright. Greetings!

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Comment by tabuna** [comment]
Hello, I invited you to the [organization](https://github.com/orchidsoftware).

Thank you

**Comment by nunojesus** [comment]
Thank you for the invitation, it will be a pleasure for me to contribute to this project.
I dont understand why my pull request didnt pass one of the verifications?  I think I did everything allright.
Greetings!

**Comment by tabuna** [comment]
Oh, do not worry. This is a software [error](https://github.com/facebook/php-webdriver/issues/520#issue-283248700) with one of the components.
Translations are not checked, (I do not know of such solutions for this, can you advise?)

**Comment by nunojesus** [comment]
Well, Im new with github, I have lot to learn, so at the moment I cant give you an advice, but I will search about it. 
Who is going to merged my pull request? 
What files do you want me to translate first?

**Comment by tabuna** [comment]
We have [documentation](https://github.com/orchidsoftware/platform/tree/master/docs) and [application](https://github.com/orchidsoftware/platform/tree/master/resources/lang) files.

You can translate in any order.

As soon as there is a complete translation of the documentation, it will be immediately available on the website. The translation of the application will be available only with the next release.


I am very worried about the issue of supporting documentation in the actual state, I do not think this is a one-time job.

**Comment by tabuna** [comment]
Do not worry, in any case I will do it. I just suggested a more convenient approach;)

I appreciate your work. :thumbsup:

**Comment by nunojesus** [comment]
Thank you for your words! Even today I will do some more translations of your project and when I finish the project I can also translate to brazilian portuguese if you want.
Greetings

**Pull request merged**
