### PR TITLE
date range filter

### LINKED ISSUE #1327: Date Range filter
**Is your feature request related to a problem? Please describe.**
On a screen, I need to filter the data between two dates (for example on an orders report)

**Describe the solution you'd like**
Provide a TD::FILTER_DATE_RANGE

**Describe alternatives you've considered**
Provide a date range filter option in command bar to add date_from and date_to as GET vars in url

### PR DESCRIPTION
**Pull request by reynoldspaul**
Fixes #1327

## Proposed Changes

  - add `FILTER_DATE_RANGE` to TD filter options
  - create date_range filter blade partial
  - filter `$query->whereBetween` in `HttpFilter.php`

### CODE REVIEW

**Comment by RaiserWeb** [comment]
@tabuna have you reviewed this, did you find any issues?

**Comment by tabuna** [comment]
Hi @RaiserWeb, sorry to wait. Can you add tests? You can [find examples here](https://github.com/orchidsoftware/platform/blob/master/tests/Unit/HttpFilterTest.php).

**Comment by mucan54** [comment]
It is very important feature, i tested it in my local environment works well i looking forward it's to be merged.

**Comment by AidasK** [comment]
Similar MR https://github.com/orchidsoftware/platform/pull/1927

Can somebody review it?

**Pull request closed without merging**
