### PR TITLE
feature/fildTabs

### PR DESCRIPTION
**Pull request by DenoBY**
add field tabs

### CODE REVIEW

**Comment by DenoBY** [comment]
@tabuna Здравствуйте, пр в таком виде вас устроит?

**Comment by tabuna** [comment]
Hi @DenoBY please describe the changes you are proposing, as well as the benefits and uses.

**Comment by DenoBY** [comment]
> Привет@DenoBYпожалуйста, опишите изменения, которые вы предлагаете, а также преимущества и способы использования.

This allows tabs to be used in the context of Layout Rows.

Here is an example of using such tabs
https://i.ibb.co/NLptv5Z/2022-08-24-22-27-44.png

thanks to these tabs, I save space and keep a neat design

**Comment by DenoBY** [comment]
@tabuna why is pull request not accepted?

**Pull request closed without merging**
