### PR TITLE
Add missing property to the Dashboard class - currentScreen

### PR DESCRIPTION
**Pull request by MunGell**
## Proposed Changes

  - Add `$currentScreen` private property in `Dashboard` class as it is used in `setCurrentScreen` and `setCurrentScreen`. Throws PHP Notice in console, breaks CI tests

### CODE REVIEW

**Comment by MunGell** [comment]
Thats strange, maybe I've branched from a wrong place, let me check

**Comment by MunGell** [comment]
Looks like there was a force push to the branch

**Comment by tabuna** [comment]
My thousand apologies, initially said the wrong thread and rewrote it

**Comment by MunGell** [comment]
Was fixed already

**Pull request closed without merging**
