### PR TITLE
Tagalog Translation for access.md

### PR DESCRIPTION
**Pull request by caratzky**
File Location: docs/en/access.md

Fixes #

## Proposed Changes

  - Tagalog Translation
  -
  -

### CODE REVIEW

**Comment by tabuna** [comment]
Why was the English file deleted?


We can publish files under the same names, but in different directories.
```
docs -> en
     -> ru
     -> pl
     -> ch
     -> etc
```

**Comment by caratzky** [comment]
Because it is made on the Filipino Translation Branch Sir

**Comment by caratzky** [comment]
Ah I get it. I'm very sorry. I'll change it immediately Sir. Sorry for the incovenience

**Comment by caratzky** [comment]
@tabuna will the orignal english file be deleted if this PR is merged? I think not. Because it will be merged on a different branch like what I've been doing in the other github projects. Just merge it on the branch I created - the filipino translations branch. Hoping to hear your feedback, so I could go on smoothly. Thank you.

**Comment by PSalador** [comment]
I make dir `ph` for Filipino language.
There you need to add files without changing the name.

**Comment by caratzky** [comment]
Yes, that's what I was waiting, because I could not create a folder. Thank you very much @PSalador :)

**Comment by PSalador** [comment]
See how create folder in github.
orchid15

**Comment by caratzky** [comment]
Thank you very much @PSalador  Hehe. I'll follow that. God bless.

**Comment by caratzky** [comment]
@tabuna  and @PSalador  for our translation contributions to be accepted by Utopian, Utopian moderators demand to see a merged pull request, but if I do the editing in the Filipino Translations branch, there won't be any such. I'm sorry for bothering you so much about this. But to motivate us to do our contributions, we badly need the rewards from utopian. This is also for the sake of the future translators for other languages who may come by to help.

**Comment by caratzky** [comment]
Thank you. I'll go on doing the translations then. God bless.

**Comment by tabuna** [comment]
Translations are automatically updated on the website.
As soon as the file is translated [documentation](https://github.com/orchidsoftware/platform/blob/master/docs/ru/documentation.md). 

The translation can be viewed on the website.

**Comment by caratzky** [comment]
Okay Thank you for the information @tabuna :)

**Comment by tabuna** [comment]
Please take information from the Russian file. In most cases, it is more extensive.
I'm grateful for your work. **Thank you!**

**Comment by caratzky** [comment]
Okay sir. Thank you, more especially for entrusting me this work. I'll definitely invite all other translators for other languages to help.

**Pull request merged**
