### PR TITLE
Update Screen.php

### PR DESCRIPTION
**Pull request by vladitot**
Incorrect parameters substitution in method like "remove" at UserScreen

### CODE REVIEW

**Comment by vladitot** [comment]
@tabuna hi! I don't really know why no-one more noticed this bug.
But there is a problem, when you have Button::method('remove') and public function remove(User $user) 
User is with empty attributes. That is because first argument on callMethod is "route url". But it should be last argument. I think it was in platform 7.*
Or maybe not. So, please, review this request and emit patch please.
Have a good day!

**Comment by tabuna** [comment]
Hey @vladitot.
 I am not experiencing any problem with deleting users. 
How can I reproduce your problem?

**Comment by vladitot** [comment]
I will try show receipt in few hours.

**Comment by vladitot** [comment]
I'm glad sorry. I found what I lost. My nginx was set up the way, an additional parameter added on each query. Laravel thought that there is one more query parameter, and route parameters were mapping incorrectly. I think my fix in this pull request can save people in same situation, but if there is no same situations - just close my pull request.

**Comment by tabuna** [comment]
I don't think it needs to be changed now. 
But I think it would be great to describe the problem and its solution for those who will face it in the future.

**Pull request closed without merging**
