### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected a dependency for the `laravel/framework`. Unless you have a special requirement for depending on the entire Laravel framework, it's recommended to add dependencies for the specific `illuminate` packages instead.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/orchidsoftware/platform/pull/2513/commits/a8654af9275632bb981b9518c95e835142cdd483?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/platform.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "orchid/platform": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by AndrewNovikof** [comment]
Pls rerun jobs. Stable version is released

**Comment by gulyavcevvv** [comment]
up

**Comment by tabuna** [comment]
Hi there! The Orchid for Laravel 10 update is coming out this month, although I don't have an exact date just yet. It's not just an upgrade to Laravel 10 - it's also a major release of Orchid, version 14.0, with lots of new features and enhancements.

I'm sorry for any delays you may have experienced. Due to personal reasons, I had to reschedule my timeline. But rest assured, I'm working hard to ensure that the release meets my high standards and is worth the wait.

To stay updated on my progress, check out Twitter or previous chat messages. I'm excited to share the new version of Orchid with you soon!

**Pull request closed without merging**
