### PR TITLE
Fix scope not working in Relation

### PR DESCRIPTION
**Pull request by yxuko**
This fixes Relation scope not working

**Code**
`Relation::make('chief.')->fromModel(User::class, 'name')->applyScope('bureau')`

**Expected behavior**
Getting results and can search results

**Actual behavior**
Getting no results and doing a search results in :
`Cannot use object of type Illuminate\Database\Query\Builder as array`

### CODE REVIEW

**Comment by tabuna** [comment]
Hi, this is a good change, but it can cause problems in existing applications.

Where before it is written:

```php
public function scopeBureau() {
   return ...->get();
}
```

It can be called twice. What will lead to an error.
Can we try to add verification to satisfy both conditions?

**Comment by yxuko** [comment]
Adding `->get()` in function scopeBureau() causes scope to return collection instead of query which is needed when calling `User::bureau()` in list screen

**Comment by tabuna** [comment]
Ok, let's do the following. I wrote a test in a [branch](https://github.com/orchidsoftware/platform/tree/issue/961_relation)  that would check all possible return values:

```php
/**
 * @param \Illuminate\Database\Eloquent\Builder $query
 *
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeAsBuilder(Builder $query) : Builder
{
    return $query->where('name', 'RelationTest');
}

/**
 * @param \Illuminate\Database\Eloquent\Builder $query
 *
 * @return \Illuminate\Support\Collection
 */
public function scopeAsCollection(Builder $query) : Collection
{
    return $query->where('name', 'RelationTest')->get();
}

/**
 * @param \Illuminate\Database\Eloquent\Builder $query
 *
 * @return array
 */
public function scopeAsArray(Builder $query): array
{
    return $query->where('name', 'RelationTest')->get()->all();
}
```

https://github.com/orchidsoftware/platform/blob/d92df5ade70ce5667c415bfa6c0b5d7d2680fda7/tests/Feature/Platform/RelationsTest.php

Can you change this so that it works perfectly in all cases?

**Comment by tabuna** [comment]
Thank!

**Pull request merged**
